name: Jekyll Test
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed
permalink: /:title
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      icon: "label"
      jsarr:
      - js/main.js
