name: Jekyll Test
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed
permalink: /:categories/:title
include: 
  - ".htaccess"
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      icon: "label"
      jsd:
        - js/dependencies/foreach.js
        - js/dependencies/load-script.js
        - js/dependencies/pjax.js
      jsarr:
        - js/waves.js
        - js/main.js
gems:
  - jekyll-sitemap
